format_version: 5
pipelines:
  dobby-service-dev:
    group: paathshaala
    materials:
      repo:
        git: git@github.com:roppenlabs/dobby-service.git
        branch: develop
    template: go-hermes-dev
    parameters:
      app: dobby-service
      environment: development
      namespace: services
      buildMode: buildpack
      runtime-version: 1.24.1
      alpine-version: 3.20
  dobby-service-staging:
    group: paathshaala
    materials:
      repo:
        git: git@github.com:roppenlabs/dobby-service.git
        branch: release
    template: go-hermes-stage
    parameters:
      app: dobby-service
      environment: staging
      namespace: services
      buildMode: buildpack
      runtime-version: 1.24.1
      alpine-version: 3.20
