// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/roppenlabs/dobby-service/internal/server (interfaces: Middleware)

// Package server is a generated GoMock package.
package server

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
)

// MockMiddleware is a mock of Middleware interface.
type MockMiddleware struct {
	ctrl     *gomock.Controller
	recorder *MockMiddlewareMockRecorder
}

// MockMiddlewareMockRecorder is the mock recorder for MockMiddleware.
type MockMiddlewareMockRecorder struct {
	mock *MockMiddleware
}

// NewMockMiddleware creates a new mock instance.
func NewMockMiddleware(ctrl *gomock.Controller) *MockMiddleware {
	mock := &MockMiddleware{ctrl: ctrl}
	mock.recorder = &MockMiddlewareMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMiddleware) EXPECT() *MockMiddlewareMockRecorder {
	return m.recorder
}

// Authenticate mocks base method.
func (m *MockMiddleware) Authenticate() gin.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authenticate")
	ret0, _ := ret[0].(gin.HandlerFunc)
	return ret0
}

// Authenticate indicates an expected call of Authenticate.
func (mr *MockMiddlewareMockRecorder) Authenticate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authenticate", reflect.TypeOf((*MockMiddleware)(nil).Authenticate))
}

// EnforceRouteAuthorization mocks base method.
func (m *MockMiddleware) EnforceRouteAuthorization() gin.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnforceRouteAuthorization")
	ret0, _ := ret[0].(gin.HandlerFunc)
	return ret0
}

// EnforceRouteAuthorization indicates an expected call of EnforceRouteAuthorization.
func (mr *MockMiddlewareMockRecorder) EnforceRouteAuthorization() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnforceRouteAuthorization", reflect.TypeOf((*MockMiddleware)(nil).EnforceRouteAuthorization))
}

// ModuleListing mocks base method.
func (m *MockMiddleware) ModuleListing() gin.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModuleListing")
	ret0, _ := ret[0].(gin.HandlerFunc)
	return ret0
}

// ModuleListing indicates an expected call of ModuleListing.
func (mr *MockMiddlewareMockRecorder) ModuleListing() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModuleListing", reflect.TypeOf((*MockMiddleware)(nil).ModuleListing))
}

// OperationListing mocks base method.
func (m *MockMiddleware) OperationListing() gin.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OperationListing")
	ret0, _ := ret[0].(gin.HandlerFunc)
	return ret0
}

// OperationListing indicates an expected call of OperationListing.
func (mr *MockMiddlewareMockRecorder) OperationListing() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OperationListing", reflect.TypeOf((*MockMiddleware)(nil).OperationListing))
}
