// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/roppenlabs/dobby-service/internal/clients/entities (interfaces: EntitiesClient)
//
// Generated by this command:
//
//	mockgen -destination client_mock.go -package=entitiesclient . EntitiesClient
//

// Package entitiesclient is a generated GoMock package.
package entitiesclient

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEntitiesClient is a mock of EntitiesClient interface.
type MockEntitiesClient struct {
	ctrl     *gomock.Controller
	recorder *MockEntitiesClientMockRecorder
	isgomock struct{}
}

// MockEntitiesClientMockRecorder is the mock recorder for MockEntitiesClient.
type MockEntitiesClientMockRecorder struct {
	mock *MockEntitiesClient
}

// NewMockEntitiesClient creates a new mock instance.
func NewMockEntitiesClient(ctrl *gomock.Controller) *MockEntitiesClient {
	mock := &MockEntitiesClient{ctrl: ctrl}
	mock.recorder = &MockEntitiesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEntitiesClient) EXPECT() *MockEntitiesClientMockRecorder {
	return m.recorder
}

// GetRolesFromEmail mocks base method.
func (m *MockEntitiesClient) GetRolesFromEmail(email string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRolesFromEmail", email)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRolesFromEmail indicates an expected call of GetRolesFromEmail.
func (mr *MockEntitiesClientMockRecorder) GetRolesFromEmail(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRolesFromEmail", reflect.TypeOf((*MockEntitiesClient)(nil).GetRolesFromEmail), email)
}
