// Code generated by mockery. DO NOT EDIT.

package helloworld

import (
	"github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

// HelloWorld provides a mock function with given fields:
func (_m *MockService) HelloWorld() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}