// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/roppenlabs/dobby-service/internal/modules/kafka/validators (interfaces: Validator)
//
// Generated by this command:
//
//	mockgen -destination validator_mock.go -package=validators . Validator
//

// Package validators is a generated GoMock package.
package validators

import (
	reflect "reflect"

	kafkatypes "github.com/roppenlabs/dobby-service/internal/modules/kafka/types"
	gomock "go.uber.org/mock/gomock"
)

// MockValidator is a mock of Validator interface.
type MockValidator struct {
	ctrl     *gomock.Controller
	recorder *MockValidatorMockRecorder
	isgomock struct{}
}

// MockValidatorMockRecorder is the mock recorder for MockValidator.
type MockValidatorMockRecorder struct {
	mock *MockValidator
}

// NewMockValidator creates a new mock instance.
func NewMockValidator(ctrl *gomock.Controller) *MockValidator {
	mock := &MockValidator{ctrl: ctrl}
	mock.recorder = &MockValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidator) EXPECT() *MockValidatorMockRecorder {
	return m.recorder
}

// ValidateCreateTopicRequest mocks base method.
func (m *MockValidator) ValidateCreateTopicRequest(req *kafkatypes.CreateTopicRequest) (bool, *kafkatypes.KafkaError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateCreateTopicRequest", req)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(*kafkatypes.KafkaError)
	return ret0, ret1
}

// ValidateCreateTopicRequest indicates an expected call of ValidateCreateTopicRequest.
func (mr *MockValidatorMockRecorder) ValidateCreateTopicRequest(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateCreateTopicRequest", reflect.TypeOf((*MockValidator)(nil).ValidateCreateTopicRequest), req)
}
