// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/accesscontrol/actionMapping.go
//
// Generated by this command:
//
//	mockgen -source=./internal/accesscontrol/actionMapping.go -destination=./internal/accesscontrol/actionMapping_mock.go -package=accesscontrol
//

// Package accesscontrol is a generated GoMock package.
package accesscontrol

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockActionMapping is a mock of ActionMapping interface.
type MockActionMapping struct {
	ctrl     *gomock.Controller
	recorder *MockActionMappingMockRecorder
	isgomock struct{}
}

// MockActionMappingMockRecorder is the mock recorder for MockActionMapping.
type MockActionMappingMockRecorder struct {
	mock *MockActionMapping
}

// NewMockActionMapping creates a new mock instance.
func NewMockActionMapping(ctrl *gomock.Controller) *MockActionMapping {
	mock := &MockActionMapping{ctrl: ctrl}
	mock.recorder = &MockActionMappingMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActionMapping) EXPECT() *MockActionMappingMockRecorder {
	return m.recorder
}

// GetValidAction mocks base method.
func (m *MockActionMapping) GetValidAction(module, opid string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidAction", module, opid)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValidAction indicates an expected call of GetValidAction.
func (mr *MockActionMappingMockRecorder) GetValidAction(module, opid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidAction", reflect.TypeOf((*MockActionMapping)(nil).GetValidAction), module, opid)
}

// GetValidOpIds mocks base method.
func (m *MockActionMapping) GetValidOpIds(module string, allowedActions []string) (map[string]bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidOpIds", module, allowedActions)
	ret0, _ := ret[0].(map[string]bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValidOpIds indicates an expected call of GetValidOpIds.
func (mr *MockActionMappingMockRecorder) GetValidOpIds(module, allowedActions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidOpIds", reflect.TypeOf((*MockActionMapping)(nil).GetValidOpIds), module, allowedActions)
}

// LoadRBACMap mocks base method.
func (m *MockActionMapping) LoadRBACMap(path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadRBACMap", path)
	ret0, _ := ret[0].(error)
	return ret0
}

// LoadRBACMap indicates an expected call of LoadRBACMap.
func (mr *MockActionMappingMockRecorder) LoadRBACMap(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadRBACMap", reflect.TypeOf((*MockActionMapping)(nil).LoadRBACMap), path)
}
