// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/roppenlabs/dobby-service/internal/accesscontrol (interfaces: AccessControlAdapter)
//
// Generated by this command:
//
//	mockgen -destination=adapter_mock.go -package=accesscontrol . AccessControlAdapter
//

// Package accesscontrol is a generated GoMock package.
package accesscontrol

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAccessControlAdapter is a mock of AccessControlAdapter interface.
type MockAccessControlAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockAccessControlAdapterMockRecorder
	isgomock struct{}
}

// MockAccessControlAdapterMockRecorder is the mock recorder for MockAccessControlAdapter.
type MockAccessControlAdapterMockRecorder struct {
	mock *MockAccessControlAdapter
}

// NewMockAccessControlAdapter creates a new mock instance.
func NewMockAccessControlAdapter(ctrl *gomock.Controller) *MockAccessControlAdapter {
	mock := &MockAccessControlAdapter{ctrl: ctrl}
	mock.recorder = &MockAccessControlAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccessControlAdapter) EXPECT() *MockAccessControlAdapterMockRecorder {
	return m.recorder
}

// Enforce mocks base method.
func (m *MockAccessControlAdapter) Enforce(params ...any) (bool, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range params {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Enforce", varargs...)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Enforce indicates an expected call of Enforce.
func (mr *MockAccessControlAdapterMockRecorder) Enforce(params ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enforce", reflect.TypeOf((*MockAccessControlAdapter)(nil).Enforce), params...)
}

// GetImplicitActionsForRole mocks base method.
func (m *MockAccessControlAdapter) GetImplicitActionsForRole(role, module string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImplicitActionsForRole", role, module)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetImplicitActionsForRole indicates an expected call of GetImplicitActionsForRole.
func (mr *MockAccessControlAdapterMockRecorder) GetImplicitActionsForRole(role, module any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImplicitActionsForRole", reflect.TypeOf((*MockAccessControlAdapter)(nil).GetImplicitActionsForRole), role, module)
}

// GetImplicitModulesForRole mocks base method.
func (m *MockAccessControlAdapter) GetImplicitModulesForRole(role string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImplicitModulesForRole", role)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetImplicitModulesForRole indicates an expected call of GetImplicitModulesForRole.
func (mr *MockAccessControlAdapterMockRecorder) GetImplicitModulesForRole(role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImplicitModulesForRole", reflect.TypeOf((*MockAccessControlAdapter)(nil).GetImplicitModulesForRole), role)
}
