// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/roppenlabs/dobby-service/internal/accesscontrol (interfaces: AccessControlService)
//
// Generated by this command:
//
//	mockgen -destination=service_mock.go -package=accesscontrol . AccessControlService
//

// Package accesscontrol is a generated GoMock package.
package accesscontrol

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAccessControlService is a mock of AccessControlService interface.
type MockAccessControlService struct {
	ctrl     *gomock.Controller
	recorder *MockAccessControlServiceMockRecorder
	isgomock struct{}
}

// MockAccessControlServiceMockRecorder is the mock recorder for MockAccessControlService.
type MockAccessControlServiceMockRecorder struct {
	mock *MockAccessControlService
}

// NewMockAccessControlService creates a new mock instance.
func NewMockAccessControlService(ctrl *gomock.Controller) *MockAccessControlService {
	mock := &MockAccessControlService{ctrl: ctrl}
	mock.recorder = &MockAccessControlServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccessControlService) EXPECT() *MockAccessControlServiceMockRecorder {
	return m.recorder
}

// GetPermittedActionsForRoles mocks base method.
func (m *MockAccessControlService) GetPermittedActionsForRoles(roles []string, module string) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPermittedActionsForRoles", roles, module)
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetPermittedActionsForRoles indicates an expected call of GetPermittedActionsForRoles.
func (mr *MockAccessControlServiceMockRecorder) GetPermittedActionsForRoles(roles, module any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPermittedActionsForRoles", reflect.TypeOf((*MockAccessControlService)(nil).GetPermittedActionsForRoles), roles, module)
}

// GetPermittedModulesForRoles mocks base method.
func (m *MockAccessControlService) GetPermittedModulesForRoles(roles []string) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPermittedModulesForRoles", roles)
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetPermittedModulesForRoles indicates an expected call of GetPermittedModulesForRoles.
func (mr *MockAccessControlServiceMockRecorder) GetPermittedModulesForRoles(roles any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPermittedModulesForRoles", reflect.TypeOf((*MockAccessControlService)(nil).GetPermittedModulesForRoles), roles)
}

// VerifyActionForRoles mocks base method.
func (m *MockAccessControlService) VerifyActionForRoles(roles []string, module, action string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyActionForRoles", roles, module, action)
	ret0, _ := ret[0].(bool)
	return ret0
}

// VerifyActionForRoles indicates an expected call of VerifyActionForRoles.
func (mr *MockAccessControlServiceMockRecorder) VerifyActionForRoles(roles, module, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyActionForRoles", reflect.TypeOf((*MockAccessControlService)(nil).VerifyActionForRoles), roles, module, action)
}
