// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/roppenlabs/dobby-service/internal/modules/kafka (interfaces: KafkaHelper)
//
// Generated by this command:
//
//	mockgen -destination=kafkahelper_mock.go -package=kafka . KafkaHelper
//

// Package kafka is a generated GoMock package.
package kafkahelpers

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockKafkaHelper is a mock of KafkaHelper interface.
type MockKafkaHelper struct {
	ctrl     *gomock.Controller
	recorder *MockKafkaHelperMockRecorder
	isgomock struct{}
}

// MockKafkaHelperMockRecorder is the mock recorder for MockKafkaHelper.
type MockKafkaHelperMockRecorder struct {
	mock *MockKafkaHelper
}

// NewMockKafkaHelper creates a new mock instance.
func NewMockKafkaHelper(ctrl *gomock.Controller) *MockKafkaHelper {
	mock := &MockKafkaHelper{ctrl: ctrl}
	mock.recorder = &MockKafkaHelperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKafkaHelper) EXPECT() *MockKafkaHelperMockRecorder {
	return m.recorder
}

// CreateClient mocks base method.
func (m *MockKafkaHelper) CreateClient(clusterUrl string) (AdminClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateClient", clusterUrl)
	ret0, _ := ret[0].(AdminClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateClient indicates an expected call of CreateClient.
func (mr *MockKafkaHelperMockRecorder) CreateClient(clusterUrl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateClient", reflect.TypeOf((*MockKafkaHelper)(nil).CreateClient), clusterUrl)
}
