// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/roppenlabs/dobby-service/internal/modules/kafka/helpers (interfaces: KafkaClient)
//
// Generated by this command:
//
//	mockgen -destination=kafkaclient_mock.go -package=kafkahelpers . KafkaClient
//

// Package kafkahelpers is a generated GoMock package.
package kafkahelpers

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockKafkaClient is a mock of KafkaClient interface.
type MockKafkaClient struct {
	ctrl     *gomock.Controller
	recorder *MockKafkaClientMockRecorder
	isgomock struct{}
}

// MockKafkaClientMockRecorder is the mock recorder for MockKafkaClient.
type MockKafkaClientMockRecorder struct {
	mock *MockKafkaClient
}

// NewMockKafkaClient creates a new mock instance.
func NewMockKafkaClient(ctrl *gomock.Controller) *MockKafkaClient {
	mock := &MockKafkaClient{ctrl: ctrl}
	mock.recorder = &MockKafkaClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKafkaClient) EXPECT() *MockKafkaClientMockRecorder {
	return m.recorder
}

// CreateClient mocks base method.
func (m *MockKafkaClient) CreateClient(clusterUrl string) (AdminClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateClient", clusterUrl)
	ret0, _ := ret[0].(AdminClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateClient indicates an expected call of CreateClient.
func (mr *MockKafkaClientMockRecorder) CreateClient(clusterUrl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateClient", reflect.TypeOf((*MockKafkaClient)(nil).CreateClient), clusterUrl)
}
