// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/roppenlabs/dobby-service/internal/modules/kafka/helpers (interfaces: AdminClient)
//
// Generated by this command:
//
//	mockgen -destination=repository_mock.go -package=kafkahelpers . AdminClient
//

// Package kafkahelpers is a generated GoMock package.
package kafkahelpers

import (
	context "context"
	reflect "reflect"

	kafka "github.com/confluentinc/confluent-kafka-go/kafka"
	gomock "go.uber.org/mock/gomock"
)

// MockAdminClient is a mock of AdminClient interface.
type MockAdminClient struct {
	ctrl     *gomock.Controller
	recorder *MockAdminClientMockRecorder
	isgomock struct{}
}

// MockAdminClientMockRecorder is the mock recorder for MockAdminClient.
type MockAdminClientMockRecorder struct {
	mock *MockAdminClient
}

// NewMockAdminClient creates a new mock instance.
func NewMockAdminClient(ctrl *gomock.Controller) *MockAdminClient {
	mock := &MockAdminClient{ctrl: ctrl}
	mock.recorder = &MockAdminClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminClient) EXPECT() *MockAdminClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockAdminClient) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockAdminClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockAdminClient)(nil).Close))
}

// CreateTopics mocks base method.
func (m *MockAdminClient) CreateTopics(ctx context.Context, topics []kafka.TopicSpecification) ([]kafka.TopicResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTopics", ctx, topics)
	ret0, _ := ret[0].([]kafka.TopicResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTopics indicates an expected call of CreateTopics.
func (mr *MockAdminClientMockRecorder) CreateTopics(ctx, topics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTopics", reflect.TypeOf((*MockAdminClient)(nil).CreateTopics), ctx, topics)
}

// DeleteTopic mocks base method.
func (m *MockAdminClient) DeleteTopic(ctx context.Context, topic string) ([]kafka.TopicResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTopic", ctx, topic)
	ret0, _ := ret[0].([]kafka.TopicResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTopic indicates an expected call of DeleteTopic.
func (mr *MockAdminClientMockRecorder) DeleteTopic(ctx, topic any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTopic", reflect.TypeOf((*MockAdminClient)(nil).DeleteTopic), ctx, topic)
}

// GetMetadata mocks base method.
func (m *MockAdminClient) GetMetadata(topic *string, allTopics bool, timeoutMs int) (*kafka.Metadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetadata", topic, allTopics, timeoutMs)
	ret0, _ := ret[0].(*kafka.Metadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetadata indicates an expected call of GetMetadata.
func (mr *MockAdminClientMockRecorder) GetMetadata(topic, allTopics, timeoutMs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetadata", reflect.TypeOf((*MockAdminClient)(nil).GetMetadata), topic, allTopics, timeoutMs)
}

// GetRetentionMs mocks base method.
func (m *MockAdminClient) GetRetentionMs(topic string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRetentionMs", topic)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRetentionMs indicates an expected call of GetRetentionMs.
func (mr *MockAdminClientMockRecorder) GetRetentionMs(topic any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRetentionMs", reflect.TypeOf((*MockAdminClient)(nil).GetRetentionMs), topic)
}
