// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/roppenlabs/dobby-service/internal/utils (interfaces: ClusterUtils)
//
// Generated by this command:
//
//	mockgen -destination=clusterUtils_mock.go -package=utils . ClusterUtils
//

// Package utils is a generated GoMock package.
package utils

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClusterUtils is a mock of ClusterUtils interface.
type MockClusterUtils struct {
	ctrl     *gomock.Controller
	recorder *MockClusterUtilsMockRecorder
	isgomock struct{}
}

// MockClusterUtilsMockRecorder is the mock recorder for MockClusterUtils.
type MockClusterUtilsMockRecorder struct {
	mock *MockClusterUtils
}

// NewMockClusterUtils creates a new mock instance.
func NewMockClusterUtils(ctrl *gomock.Controller) *MockClusterUtils {
	mock := &MockClusterUtils{ctrl: ctrl}
	mock.recorder = &MockClusterUtilsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClusterUtils) EXPECT() *MockClusterUtilsMockRecorder {
	return m.recorder
}

// GetClusterUrlFromClusterId mocks base method.
func (m *MockClusterUtils) GetClusterUrlFromClusterId(cid string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClusterUrlFromClusterId", cid)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClusterUrlFromClusterId indicates an expected call of GetClusterUrlFromClusterId.
func (mr *MockClusterUtilsMockRecorder) GetClusterUrlFromClusterId(cid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClusterUrlFromClusterId", reflect.TypeOf((*MockClusterUtils)(nil).GetClusterUrlFromClusterId), cid)
}

// GetTimeoutForGetMetadataFromConfig mocks base method.
func (m *MockClusterUtils) GetTimeoutForGetMetadataFromConfig() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTimeoutForGetMetadataFromConfig")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetTimeoutForGetMetadataFromConfig indicates an expected call of GetTimeoutForGetMetadataFromConfig.
func (mr *MockClusterUtilsMockRecorder) GetTimeoutForGetMetadataFromConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTimeoutForGetMetadataFromConfig", reflect.TypeOf((*MockClusterUtils)(nil).GetTimeoutForGetMetadataFromConfig))
}
