package modules

const (
	MODULE_NOT_FOUND                 = "MODULE_NOT_FOUND"
	OPERATION_NOT_FOUND              = "OPERATION_NOT_FOUND"
	SCHEMA_NOT_FOUND                 = "SCHEMA_NOT_FOUND"
	MISSING_MODULE_ID                = "MISSING_MODULE_ID"
	MISSING_OPERATION_ID             = "MISSING_OPERATION_ID"
	CLUSTER_URL_NOT_FOUND            = "CLUSTER_URL_NOT_FOUND"
	KAFKA_CLIENT_CREATION_FAILED     = "KAFKA_CLIENT_CREATION_FAILED"
	TOPIC_CREATION_FAILED            = "TOPIC_CREATION_FAILED"
	TOPIC_DELETION_FAILED            = "TOPIC_DELETION_FAILED"
	TOPIC_NOT_FOUND                  = "TOPIC_NOT_FOUND"
	ROLE_NOT_FOUND                   = "ROLE_NOT_FOUND"
	TOPIC_AUTHORIZATION_FAILED       = "TOPIC_AUTHORIZATION_FAILED"
	INVALID_REQUEST_BODY             = "INVALID_REQUEST_BODY"
	INTERNAL_SERVER_ERROR            = "INTERNAL_SERVER_ERROR"
	ERROR_DELETING_KAFKA             = "ERROR_DELETING_KAFKA"
	BAD_REQUEST                      = "BAD_REQUEST"
	INTERNAL_ERROR                   = "INTERNAL_ERROR"
	ACCESS_DENIED                    = "ACCESS_DENIED"
	ACTIONMAP_NOT_FOUND              = "ACTIONMAP_NOT_FOUND"
	FORBIDDEN                        = "FORBIDDEN"
	UNAUTHORIZED                     = "UNAUTHORIZED"
	KAFKA_TOPIC_DELETION_ERROR       = "KAFKA_TOPIC_DELETION_ERROR"
	KAFKA_TOPIC_AUTHORIZATION_FAILED = "KAFKA_TOPIC_AUTHORIZATION_FAILED"
	KAFKA_TOPIC_EXISTS               = "KAFKA_TOPIC_EXISTS"
	KAFKA_TOPIC_CREATION_ERROR       = "KAFKA_TOPIC_CREATION_ERROR"
	INVALID_KAFKA_CONFIG             = "INVALID_KAFKA_CONFIG"
)

const (
	RBAC_MODEL_CONF_FILE_PATH = "internal/accesscontrol/rbac_model.conf"
	RBAC_POLICY_FILE_PATH     = "internal/accesscontrol/policy.csv"
	DatabaseYAML_FILE_PATH    = "staticfiles/database.yaml"
	SchemaYAML_FILE_PATH      = "staticfiles/schema.yaml"
)
