// Code generated by MockGen. DO NOT EDIT.
// Source: internal/modules/service.go

// Package modules is a generated GoMock package.
package modules

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetFilteredOperations mocks base method.
func (m *MockService) GetFilteredOperations(moduleID string, allowedActions []string) ([]Operations, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilteredOperations", moduleID, allowedActions)
	ret0, _ := ret[0].([]Operations)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilteredOperations indicates an expected call of GetFilteredOperations.
func (mr *MockServiceMockRecorder) GetFilteredOperations(moduleID, allowedActions interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilteredOperations", reflect.TypeOf((*MockService)(nil).GetFilteredOperations), moduleID, allowedActions)
}

// GetModules mocks base method.
func (m *MockService) GetModules(userModules []string) ([]ModuleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModules", userModules)
	ret0, _ := ret[0].([]ModuleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetModules indicates an expected call of GetModules.
func (mr *MockServiceMockRecorder) GetModules(userModules interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModules", reflect.TypeOf((*MockService)(nil).GetModules), userModules)
}

// GetOperationDetail mocks base method.
func (m *MockService) GetOperationDetail(moduleID, operationID string) (*OperationDetailResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOperationDetail", moduleID, operationID)
	ret0, _ := ret[0].(*OperationDetailResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOperationDetail indicates an expected call of GetOperationDetail.
func (mr *MockServiceMockRecorder) GetOperationDetail(moduleID, operationID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOperationDetail", reflect.TypeOf((*MockService)(nil).GetOperationDetail), moduleID, operationID)
}
