// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/roppenlabs/dobby-service/internal/modules/kafka/services (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination=service_mock.go -package=kafkaservices . Service
//

// Package kafkaservices is a generated GoMock package.
package kafkaservices

import (
	reflect "reflect"

	kafkatypes "github.com/roppenlabs/dobby-service/internal/modules/kafka/types"
	types "github.com/roppenlabs/dobby-service/internal/types"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CreateTopic mocks base method.
func (m *MockService) CreateTopic(req *kafkatypes.CreateTopicRequest) (*kafkatypes.CreateTopicResponse, *types.ErrorResponse) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTopic", req)
	ret0, _ := ret[0].(*kafkatypes.CreateTopicResponse)
	ret1, _ := ret[1].(*types.ErrorResponse)
	return ret0, ret1
}

// CreateTopic indicates an expected call of CreateTopic.
func (mr *MockServiceMockRecorder) CreateTopic(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTopic", reflect.TypeOf((*MockService)(nil).CreateTopic), req)
}

// DeleteTopic mocks base method.
func (m *MockService) DeleteTopic(arg0 *kafkatypes.DeleteTopicRequest) (*kafkatypes.DeleteTopicResponse, *types.ErrorResponse) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTopic", arg0)
	ret0, _ := ret[0].(*kafkatypes.DeleteTopicResponse)
	ret1, _ := ret[1].(*types.ErrorResponse)
	return ret0, ret1
}

// DeleteTopic indicates an expected call of DeleteTopic.
func (mr *MockServiceMockRecorder) DeleteTopic(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTopic", reflect.TypeOf((*MockService)(nil).DeleteTopic), arg0)
}

// ListTopics mocks base method.
func (m *MockService) ListTopics(arg0 *kafkatypes.ListTopicsRequest) (*kafkatypes.ListTopicsResponse, *types.ErrorResponse) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTopics", arg0)
	ret0, _ := ret[0].(*kafkatypes.ListTopicsResponse)
	ret1, _ := ret[1].(*types.ErrorResponse)
	return ret0, ret1
}

// ListTopics indicates an expected call of ListTopics.
func (mr *MockServiceMockRecorder) ListTopics(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTopics", reflect.TypeOf((*MockService)(nil).ListTopics), arg0)
}
